import style from './bodyStyle.js'
import { View, Text,ScrollView } from 'react-native'

export default function Body(){

    return(
        <ScrollView>
            <Text style={style.text}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ultricies volutpat enim ut consequat. Donec ligula dui, lobortis in luctus ut, mollis eget justo. Phasellus ullamcorper finibus sapien, id lacinia leo tempus sit amet. Pellentesque eu feugiat erat. Nullam a tellus ipsum. Ut feugiat orci non quam aliquam condimentum vitae ut urna. Suspendisse ullamcorper, ex at consectetur finibus, elit odio hendrerit purus, sit amet pulvinar lorem tortor varius justo. Pellentesque ultricies enim semper felis dapibus tempus. Quisque luctus, sapien vitae elementum finibus, elit massa hendrerit neque, vitae gravida ex odio at diam. Etiam varius velit non semper placerat.
                Donec iaculis turpis nec purus convallis, sit amet volutpat metus posuere. Aenean consequat quis magna sed imperdiet. Curabitur dictum lorem interdum nisi vestibulum vehicula. Mauris eu elit facilisis, sodales libero fringilla, laoreet est. Vivamus fermentum diam eros, eu pellentesque ipsum tincidunt a. Quisque non orci augue. Phasellus consequat vehicula mauris quis eleifend.
                Sed eget metus pharetra, elementum quam vitae, auctor nisl. Aliquam erat volutpat. Cras pellentesque ullamcorper sapien, at bibendum nulla dignissim sed. Integer rhoncus leo eget odio rhoncus sagittis. Etiam imperdiet aliquet dapibus. Phasellus sollicitudin molestie tellus, vitae maximus magna facilisis vitae. Morbi rutrum turpis a lectus dapibus, dictum dignissim nunc efficitur. Praesent congue mi eget erat porttitor convallis. Nunc et nisl id leo vulputate tristique. Sed ut eros aliquam, ornare leo in, accumsan felis. Cras egestas leo et convallis ultrices. Etiam faucibus nulla molestie, malesuada quam et, pulvinar magna.
                Maecenas dui dolor, ultricies et hendrerit et, lacinia et velit. Nam tempus lorem enim. Nunc fringilla aliquet luctus. Proin non imperdiet diam, vel facilisis neque. Aenean nec condimentum tellus. In vulputate, mi ut efficitur convallis, dolor sapien pulvinar libero, et iaculis urna sapien non eros. Nunc dictum turpis metus, et convallis eros faucibus eget. Sed ornare, diam ut consectetur dignissim, eros nibh finibus sapien, finibus mollis urna leo vel magna. Aenean vehicula rutrum turpis a commodo. Aenean pellentesque leo non eros gravida, vel accumsan orci tincidunt. Donec luctus bibendum dui et blandit. Fusce ultrices lectus ac augue fringilla luctus.
                Maecenas egestas sapien id purus luctus congue. Ut placerat scelerisque convallis. Aenean tortor urna, bibendum vitae pellentesque imperdiet, aliquet nec augue. Fusce vulputate tincidunt porta. Vestibulum condimentum mi eget elementum vehicula. Nulla ac ligula sed nibh maximus finibus. Praesent ornare bibendum nibh, eu pretium ligula sodales eu. Nunc tempor odio a sapien tempor elementum quis ut dui. Nulla lectus augue, ullamcorper tempor dolor posuere, tempus ornare nunc. Proin neque tellus, semper quis ultricies finibus, sollicitudin quis ex. Aenean sit amet maximus mi. Pellentesque luctus purus blandit lacus fermentum rutrum.
                Maecenas egestas sapien id purus luctus congue. Ut placerat scelerisque convallis. Aenean tortor urna, bibendum vitae pellentesque imperdiet, aliquet nec augue. Fusce vulputate tincidunt porta. Vestibulum condimentum mi eget elementum vehicula. Nulla ac ligula sed nibh maximus finibus. Praesent ornare bibendum nibh, eu pretium ligula sodales eu. Nunc tempor odio a sapien tempor elementum quis ut dui. Nulla lectus augue, ullamcorper tempor dolor posuere, tempus ornare nunc. Proin neque tellus, semper quis ultricies finibus, sollicitudin quis ex. Aenean sit amet maximus mi. Pellentesque luctus purus blandit lacus fermentum rutrum.
            </Text>
        </ScrollView>
    )
}